# Generated by Django 5.2.6 on 2025-10-17 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_to_terms_and_conditions', models.BooleanField(default=False)),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('agreed_to_sms_marketing', models.BooleanField(default=False)),
                ('agreed_to_email_marketing', models.BooleanField(default=False)),
                ('agreed_to_push_notifications', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
