# Generated by Django 5.2.6 on 2025-10-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_logo', models.ImageField(upload_to='brand_request_logo/')),
                ('brand_sector', models.CharField(max_length=100)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=18)),
                ('contact_details', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='brand_documents/')),
                ('approved', models.BooleanField(default=False)),
                ('brand_request_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('account_created', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RetailerAccountRequest',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('brand', 'brand'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
