# Generated by Django 5.2.6 on 2025-10-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_brandaccountrequest_delete_retaileraccountrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandaccountrequest',
            name='address_line1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='brandaccountrequest',
            name='address_line2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_request_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
