# Generated by Django 5.2.6 on 2025-10-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_brandaccountrequest_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandaccountrequest',
            name='account_created',
        ),
    ]
