# Generated by Django 5.2.6 on 2025-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_brandaccountrequest_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandaccountrequest',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_request_logo/'),
        ),
    ]
