# Generated by Django 5.2.6 on 2025-10-14 22:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='offers.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('prefix', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional: describe the offer', null=True)),
                ('batch_size', models.PositiveIntegerField(default=1, help_text='Number of unique vouchers to generate. Set to 1 if all codes should be the same.')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: The maximum amount of the discount', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(help_text='Time and date from when the offer will begin')),
                ('end_date', models.DateTimeField(help_text='Time and date until when the offer will be valid')),
                ('usage_type', models.CharField(choices=[('single', 'Single Use'), ('multi', 'Multi Use')], default='multi', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Max total uses across all partners (null = unlimited)', null=True)),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_url', models.URLField(help_text='External website where coupon can be used')),
                ('auto_voucher_generation', models.BooleanField(default=False, help_text='Automatically generate vouchers after saving')),
                ('max_vouchers_per_user', models.PositiveIntegerField(default=1, help_text='Maximum vouchers a user can reserve from this offer')),
                ('voucher_cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours a user must wait before reserving another voucher (default: 24)')),
                ('reservation_expiry_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before an unredeemed reservation expires and returns to pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_user', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='offers.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('is_seen', models.BooleanField(default=False, help_text='Has this voucher been revealed/used by a customer')),
                ('reserved_at', models.DateTimeField(blank=True, help_text='When the voucher was reserved', null=True)),
                ('revealed_at', models.DateTimeField(blank=True, help_text='When the voucher code was first revealed to the user', null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='offers.offer')),
                ('reserved_by', models.ForeignKey(blank=True, help_text='User who has reserved this voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Code',
                'verbose_name_plural': 'Voucher Codes',
                'ordering': ['offer', 'coupon'],
            },
        ),
        migrations.CreateModel(
            name='VoucherReservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('was_used', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_logs', to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_reservations', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_logs', to='offers.voucher')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['offer', 'reserved_by'], name='offers_vouc_offer_i_d177b9_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['reserved_at'], name='offers_vouc_reserve_814f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_seen'], name='offers_vouc_is_seen_ac7b08_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherreservationlog',
            index=models.Index(fields=['user', 'offer', 'reserved_at'], name='offers_vouc_user_id_742ec6_idx'),
        ),
    ]
