# Generated by Django 5.2.6 on 2025-10-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
