# Generated by Django 5.2.6 on 2025-10-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.CharField(default='Default Product', max_length=264),
            preserve_default=False,
        ),
    ]
