# Generated by Django 5.2.6 on 2025-10-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_category_options_offer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='max_uses',
            new_name='max_usage',
        ),
    ]
