# Generated by Django 5.2.6 on 2025-10-15 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='minimum_purchase',
        ),
        migrations.AlterField(
            model_name='offer',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.subcategory'),
        ),
    ]
