# Generated by Django 5.2.6 on 2025-10-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_offer_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='reservation_expiry_minutes',
        ),
    ]
