# Generated by Django 5.2.6 on 2025-10-15 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_remove_offer_reservation_expiry_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherreservationlog',
            options={'ordering': ['-claimed_at']},
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='offers_vouc_offer_i_d177b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='offers_vouc_reserve_814f1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='offers_vouc_is_seen_ac7b08_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucherreservationlog',
            name='offers_vouc_user_id_742ec6_idx',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='is_seen',
            new_name='claimed',
        ),
        migrations.RenameField(
            model_name='voucherreservationlog',
            old_name='reserved_at',
            new_name='claimed_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='voucherreservationlog',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='voucherreservationlog',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='voucherreservationlog',
            name='was_used',
        ),
        migrations.AddField(
            model_name='voucher',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_name',
            field=models.CharField(default='voucher', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='coupon',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['offer'], name='offers_vouc_offer_i_2ecc18_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['revealed_at'], name='offers_vouc_reveale_170cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['claimed'], name='offers_vouc_claimed_4ec063_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherreservationlog',
            index=models.Index(fields=['user', 'voucher', 'claimed_at'], name='offers_vouc_user_id_a62485_idx'),
        ),
    ]
