# Generated by Django 5.2.6 on 2025-10-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_voucherreservationlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_name',
        ),
    ]
