# Generated by Django 5.2.6 on 2025-10-17 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=256)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logo/')),
                ('brand_website', models.URLField(blank=True, null=True)),
                ('brand_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('brand_owner', models.CharField(blank=True, max_length=256, null=True)),
                ('brand_document', models.FileField(blank=True, null=True, upload_to='brand_docs/')),
                ('brand_address_line1', models.CharField(blank=True, max_length=256, null=True)),
                ('brand_address_line2', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Test', max_length=100)),
                ('last_name', models.CharField(default='User', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_profile_picture/')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('retired', 'Retired'), ('volunteer', 'Volunteer')], default='employed', max_length=100)),
                ('job_details', models.TextField(choices=[('ambulance_service', 'Ambulance Service'), ('apha', 'APHA'), ('blood_bike', 'Blood Bike'), ('dental_practice', 'Dental Practice')], default='ambulance', max_length=100)),
                ('employer', models.CharField(choices=[('ambulance_service', 'Ambulance Service'), ('fire_service', 'Fire Service'), ('hm_coustguard', 'HM Coastguard'), ('independent_lifeboat', 'Independent Lifeboat'), ('nhs', 'NHS'), ('police', 'Police'), ('red_cross', 'Red Cross'), ('rnli', 'RNLI'), ('search_and_rescue', 'Search and Rescue')], default='ambulance', max_length=100)),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_status', models.BooleanField(default=False)),
                ('mandate_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
