# Generated by Django 5.2.6 on 2025-10-13 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=256)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logo/')),
                ('brand_website', models.URLField()),
                ('brand_address_line1', models.CharField(max_length=256)),
                ('brand_address_line2', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
