# Generated by Django 5.2.6 on 2025-10-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_brandprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_document',
            field=models.FileField(blank=True, null=True, upload_to='brand_docs/'),
        ),
    ]
