# Generated by Django 5.2.6 on 2025-10-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_brandprofile_brand_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_sector',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='brand_address_line1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='brand_address_line2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='brand_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
