# Generated by Django 5.2.6 on 2025-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_brandprofile_brand_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_owner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
